### ISSUE TITLE
translation.xsp

### ISSUE THREAD

**Issue by PatrickKwinten** [OpenNTF/XPages-Fusion-Application#8] opened 2016-03-10 14:05 UTC
Script interpreter error, line=24, col=120: Error calling method 'getTranslation(string, java.lang.String, java.lang.String)' on java class 'com.ibm.xsp.bluemix.services.watson.LanguageTranslation'
Target host is not specified

**Comment by briangleeson** [comment] 2016-03-13 21:12
Is this when running locally, or on Bluemix?

**Comment by briangleeson** [comment] 2016-04-12 14:17
This error should only occur in one of two situations: 
1. You are testing the app on an on-prem server. In this case you need to hard code the credentials in the respective Java class for each service.
2. You have deployed the app to Bluemix, but the required service(s) are not bound to the application.

Closing this as i believe it is not a bug, but a configuration issue

**Closed as completed by briangleeson** 2016-04-12 14:17 UTC
